import { Test, TestPack, Order, Patient, Laboratory, Nurse, Stats, Complaint, WalletTransaction, Agent } from './types';

export const mockTests: Test[] = [
  {
    id: '1',
    name: 'Bilan Sanguin Complet (NFS)',
    description: 'Numération formule sanguine complète incluant hémoglobine, globules blancs et rouges, plaquettes',
    category: 'Analyses Hématologiques',
    price: 120,
    duration: '15 min',
    preparation: 'À jeun 12 heures avant le prélèvement',
    imageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=400',
    requiresPrescription: false,
  },
  {
    id: '2',
    name: 'Test PCR COVID-19',
    description: 'Dépistage par RT-PCR avec prélèvement nasopharyngé',
    category: 'Dépistage Viral',
    price: 250,
    duration: '10 min',
    imageUrl: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=400',
    requiresPrescription: false,
  },
  {
    id: '3',
    name: 'Bilan Hépatique Complet',
    description: 'Analyse des enzymes hépatiques: ASAT, ALAT, GGT, Bilirubine, Phosphatase alcaline',
    category: 'Analyses Biochimiques',
    price: 180,
    duration: '15 min',
    preparation: 'À jeun 8 heures',
    imageUrl: 'https://images.unsplash.com/photo-1581594549595-35f6edc7b762?w=400',
    requiresPrescription: false,
  },
  {
    id: '4',
    name: 'Analyse Urinaire ECBU',
    description: 'Examen cytobactériologique des urines avec antibiogramme',
    category: 'Analyses Urinaires',
    price: 80,
    duration: '5 min',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400',
    requiresPrescription: false,
  },
  {
    id: '5',
    name: 'Bilan Thyroïdien (TSH, T3, T4)',
    description: 'Dosage hormonal complet pour évaluation de la fonction thyroïdienne',
    category: 'Analyses Endocriniennes',
    price: 220,
    duration: '15 min',
    preparation: 'Pas de préparation nécessaire',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
    requiresPrescription: true,
  },
  {
    id: '6',
    name: 'Bilan Lipidique',
    description: 'Cholestérol total, HDL, LDL, Triglycérides',
    category: 'Analyses Biochimiques',
    price: 150,
    duration: '15 min',
    preparation: 'À jeun 12 heures',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    requiresPrescription: false,
  },
  {
    id: '7',
    name: 'Glycémie à Jeun',
    description: 'Mesure du taux de sucre dans le sang',
    category: 'Analyses Biochimiques',
    price: 50,
    duration: '10 min',
    preparation: 'À jeun 8 heures',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=400',
    requiresPrescription: false,
  },
  {
    id: '8',
    name: 'Ferritine',
    description: 'Dosage de la ferritine pour évaluer les réserves en fer',
    category: 'Analyses Hématologiques',
    price: 100,
    duration: '10 min',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400',
    requiresPrescription: true,
  },
];

export const mockPacks: TestPack[] = [
  {
    id: 'pack1',
    name: 'Pack Check-up Complet Adulte',
    description: 'Bilan sanguin + bilan hépatique + bilan lipidique + glycémie',
    tests: ['1', '3', '6', '7'],
    price: 450,
    discount: 50,
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400',
  },
  {
    id: 'pack2',
    name: 'Pack Santé Femme',
    description: 'Bilan sanguin + bilan thyroïdien + analyse urinaire + ferritine',
    tests: ['1', '5', '4', '8'],
    price: 520,
    discount: 60,
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400',
  },
  {
    id: 'pack3',
    name: 'Pack Diabète',
    description: 'Glycémie + HbA1c + bilan lipidique + bilan rénal',
    tests: ['7', '6'],
    price: 280,
    discount: 20,
    imageUrl: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400',
  },
];

export const mockNurses: Nurse[] = [
  {
    id: 'n1',
    name: 'Fatima El Amrani',
    phone: '0661234567',
    license: 'INF-2024-CAS-001',
    availability: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'],
  },
  {
    id: 'n2',
    name: 'Mohammed Benjelloun',
    phone: '0662345678',
    license: 'INF-2024-CAS-002',
    availability: ['Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
  },
  {
    id: 'n3',
    name: 'Amina Tazi',
    phone: '0663456789',
    license: 'INF-2024-RAB-001',
    availability: ['Lundi', 'Mercredi', 'Vendredi', 'Samedi'],
  },
  {
    id: 'n4',
    name: 'Youssef Alami',
    phone: '0664567890',
    license: 'INF-2024-RAB-002',
    availability: ['Lundi', 'Mardi', 'Jeudi', 'Vendredi'],
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    email: 'karim.tahiri@email.com',
    name: 'Karim Tahiri',
    role: 'patient',
    phone: '0661234567',
    address: 'Résidence Al Amal, Appartement 12, Maarif, Casablanca',
    dateOfBirth: '1985-03-15',
    gender: 'M',
    createdAt: '2024-01-10',
  },
  {
    id: 'p2',
    email: 'sarah.benali@email.com',
    name: 'Sarah Benali',
    role: 'patient',
    phone: '0662345678',
    address: 'Villa 45, Hay Riad, Rabat',
    dateOfBirth: '1990-07-22',
    gender: 'F',
    createdAt: '2024-02-15',
  },
  {
    id: 'p3',
    email: 'omar.idrissi@email.com',
    name: 'Omar Idrissi',
    role: 'patient',
    phone: '0663456789',
    address: 'Immeuble Nakhil, Avenue Hassan II, Agadir',
    dateOfBirth: '1978-11-08',
    gender: 'M',
    createdAt: '2024-03-20',
  },
];

export const mockLaboratories: Laboratory[] = [
  {
    id: 'l1',
    email: 'contact@labocasa.ma',
    name: 'Dr. Amina Fassi',
    role: 'laboratory',
    labName: 'Laboratoire Casa Analyse',
    license: 'LAB-2024-CAS-001',
    address: 'Boulevard Zerktouni, Casablanca',
    phone: '0522234567',
    nurses: [mockNurses[0], mockNurses[1]],
    commission: 0.25,
    createdAt: '2023-11-01',
  },
  {
    id: 'l2',
    email: 'contact@biosante.ma',
    name: 'Dr. Hassan Alaoui',
    role: 'laboratory',
    labName: 'BioSanté Laboratoire',
    license: 'LAB-2024-RAB-001',
    address: 'Avenue Mohammed V, Rabat',
    phone: '0537456789',
    nurses: [mockNurses[2], mockNurses[3]],
    commission: 0.30,
    createdAt: '2023-12-15',
  },
  {
    id: 'l3',
    email: 'contact@medilab.ma',
    name: 'Dr. Leila Benjelloun',
    role: 'laboratory',
    labName: 'MediLab Centre',
    license: 'LAB-2024-CAS-002',
    address: 'Boulevard Anfa, Casablanca',
    phone: '0522345678',
    nurses: [mockNurses[0]],
    commission: 0.20,
    createdAt: '2024-01-10',
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'a1',
    email: 'najib.support@facilab.ma',
    name: 'Najib Khalil',
    role: 'agent',
    phone: '0665432100',
    department: 'Support Client',
    assignedComplaints: 8,
    agentType: 'manager',
    managedAgentIds: ['a2'],
    createdAt: '2024-01-01',
  },
  {
    id: 'a2',
    email: 'samira.support@facilab.ma',
    name: 'Samira Mansouri',
    role: 'agent',
    phone: '0665432101',
    department: 'Support Laboratoires',
    assignedComplaints: 5,
    agentType: 'support',
    createdAt: '2024-01-01',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    patientId: 'p1',
    patientName: 'Karim Tahiri',
    tests: [mockTests[0], mockTests[3]],
    status: 'completed',
    location: 'home',
    address: 'Résidence Al Amal, Appartement 12, Maarif, Casablanca',
    scheduledDate: '2025-01-15',
    scheduledTime: '09:00',
    assignedLaboratory: 'Laboratoire Casa Analyse',
    assignedNurse: 'Fatima El Amrani',
    price: 200,
    paid: true,
    createdAt: '2025-01-10',
    resultsUrl: 'https://example.com/results/o1.pdf',
    confirmedByLab: true,
    confirmedAt: '2025-01-14',
    walletTransactionId: 'wt1',
  },
  {
    id: 'o2',
    patientId: 'p1',
    patientName: 'Karim Tahiri',
    tests: [mockTests[1]],
    status: 'scheduled',
    location: 'laboratory',
    scheduledDate: '2025-01-22',
    scheduledTime: '14:30',
    assignedLaboratory: 'Laboratoire Casa Analyse',
    price: 250,
    paid: true,
    createdAt: '2025-01-18',
    confirmedByLab: false,
    walletTransactionId: 'wt2',
  },
  {
    id: 'o3',
    patientId: 'p2',
    patientName: 'Sarah Benali',
    tests: [mockTests[4], mockTests[5]],
    status: 'pending',
    location: 'home',
    address: 'Villa 45, Hay Riad, Rabat',
    price: 370,
    paid: false,
    createdAt: '2025-01-19',
    prescriptionUrl: '',
  },
  {
    id: 'o4',
    patientId: 'p2',
    patientName: 'Sarah Benali',
    pack: mockPacks[1],
    tests: [mockTests[0], mockTests[4], mockTests[3], mockTests[7]],
    status: 'confirmed',
    location: 'home',
    address: 'Villa 45, Hay Riad, Rabat',
    scheduledDate: '2025-01-21',
    scheduledTime: '10:00',
    assignedLaboratory: 'BioSanté Laboratoire',
    assignedNurse: 'Amina Tazi',
    price: 520,
    paid: true,
    createdAt: '2025-01-16',
    prescriptionUrl: 'https://example.com/prescriptions/o4.pdf',
    confirmedByLab: true,
    confirmedAt: '2025-01-20',
    walletTransactionId: 'wt3',
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: 'c1',
    userId: 'p1',
    userName: 'Karim Tahiri',
    userRole: 'patient',
    orderId: 'o1',
    subject: 'Retard dans la livraison des résultats',
    description: 'Les résultats promis pour le 16 janvier ne sont toujours pas disponibles',
    status: 'in_progress',
    priority: 'medium',
    assignedAgentId: 'a1',
    assignedAgentName: 'Najib Khalil',
    createdAt: '2025-01-17T10:30:00Z',
    updatedAt: '2025-01-17T14:20:00Z',
    messages: [
      {
        id: 'm1',
        senderId: 'p1',
        senderName: 'Karim Tahiri',
        senderRole: 'patient',
        message: 'Bonjour, j\'attends toujours mes résultats.',
        timestamp: '2025-01-17T10:30:00Z',
        isInternal: false,
      },
      {
        id: 'm2',
        senderId: 'a1',
        senderName: 'Najib Khalil',
        senderRole: 'agent',
        message: 'Bonjour M. Tahiri, je vérifie avec le laboratoire.',
        timestamp: '2025-01-17T14:20:00Z',
        isInternal: false,
      },
    ],
    internalNotes: [
      {
        id: 'in1',
        authorId: 'a1',
        authorName: 'Najib Khalil',
        note: 'Laboratoire a eu un problème technique, résultats en cours de validation',
        timestamp: '2025-01-17T14:25:00Z',
      },
    ],
  },
  {
    id: 'c2',
    userId: 'l1',
    userName: 'Dr. Amina Fassi',
    userRole: 'laboratory',
    subject: 'Commission incorrecte sur commande #o2',
    description: 'La commission prélevée ne correspond pas au taux convenu de 25%',
    status: 'escalated',
    priority: 'high',
    assignedAgentId: 'a2',
    assignedAgentName: 'Samira Mansouri',
    createdAt: '2025-01-18T09:15:00Z',
    updatedAt: '2025-01-18T16:45:00Z',
    messages: [],
    internalNotes: [
      {
        id: 'in2',
        authorId: 'a2',
        authorName: 'Samira Mansouri',
        note: 'Vérification en cours avec le département financier',
        timestamp: '2025-01-18T16:45:00Z',
      },
    ],
    compensation: {
      id: 'comp1',
      amount: 50,
      type: 'credit',
      status: 'pending',
    },
  },
];

export const mockWalletTransactions: WalletTransaction[] = [
  {
    id: 'wt1',
    orderId: 'o1',
    userId: 'l1',
    userRole: 'laboratory',
    type: 'payout',
    amount: 200,
    commission: 50,
    netAmount: 150,
    status: 'completed',
    createdAt: '2025-01-15',
    completedAt: '2025-01-16',
    description: 'Paiement pour commande #o1',
  },
  {
    id: 'wt2',
    orderId: 'o2',
    userId: 'l1',
    userRole: 'laboratory',
    type: 'payment',
    amount: 250,
    commission: 62.5,
    netAmount: 187.5,
    status: 'held',
    createdAt: '2025-01-18',
    description: 'Paiement en attente de confirmation - commande #o2',
  },
  {
    id: 'wt3',
    orderId: 'o4',
    userId: 'l2',
    userRole: 'laboratory',
    type: 'payment',
    amount: 520,
    commission: 156,
    netAmount: 364,
    status: 'held',
    createdAt: '2025-01-16',
    description: 'Paiement en attente de résultats - commande #o4',
  },
];

export const mockStats: Stats = {
  totalOrders: 247,
  totalRevenue: 89500,
  totalCommissions: 22375,
  activePatients: 156,
  activeLaboratories: 18,
  completedOrders: 198,
  pendingOrders: 23,
};
